-- CreateEnum
CREATE TYPE "TradeType" AS ENUM ('LONG', 'SHORT');

-- CreateEnum
CREATE TYPE "TradeStatus" AS ENUM ('OPEN', 'CLOSED');

-- AlterTable
ALTER TABLE "OrderHistory" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "status" "TradeStatus" NOT NULL DEFAULT 'OPEN',
ADD COLUMN     "symbol" TEXT NOT NULL DEFAULT 'UNKNOWN',
ADD COLUMN     "type" TEXT NOT NULL DEFAULT 'LONG',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sellPrice" DROP NOT NULL,
ALTER COLUMN "profitLoss" DROP NOT NULL;
